steps:
  
# Runs the CIS InSpec tests - but the build fails if any of the InSpec
# tests fail... Which may not be desired behaviour.
- id: 'run-inspec-cis'
  name: gcr.io/${PROJECT_ID}/inspec-gcp-cis-benchmark:latest
  args:
    - exec
    - /share/.
    - -t=gcp://
    - --input=gcp_project_id=${PROJECT_ID}
    - --reporter=cli 
    - json:/workspace/report.json

# Runs the CIS InSpec tests, but via shell.
# This way, can redirect any InSpec erros and continue with other build steps
# - id: 'run-inspec-cis'
#   name: gcr.io/${PROJECT_ID}/inspec-gcp-cis-benchmark:latest
#   entrypoint: '/bin/sh'
#   args: 
#     - '-c'
#     - |
#       cinc-auditor exec /share/. -t gcp:// \
#       --input gcp_project_id=${PROJECT_ID} \
#       --reporter cli json:/workspace/report.json | tee output.json

- id: 'Store json Report'
  waitFor: ['run-inspec-cis']
  name: gcr.io/cloud-builders/gsutil
  args:
    - cp
    - /workspace/report.json
    - gs://${_REPORTS_BUCKET}/cis-report-${BUILD_ID}.json

substitutions:
  _REPORTS_BUCKET: 'jtg-inspec-reports'
  # _INSPEC_PROFILE_DOCKER_TAG: 'latest'
