steps:

- id: 'Run InSpec'
  name: chef/inspec
  args: 
    - exec
    - /workspace
    - -t=gcp://
    - --input-file=inputs.yaml
    - --chef-license=accept
    - --reporter=cli 
    - json:/workspace/inspec_report.json

- id: 'Store json Report'
  waitFor: ['Run InSpec']
  name: gcr.io/cloud-builders/gsutil
  args:
    - cp
    - /workspace/inspec_report.json
    - gs://jtg-inspec-reports/report-${BUILD_ID}.json
